### ISSUE TITLE
Cannot cancel document

### ISSUE THREAD

**Issue by parkerself22** [eversign/eversign-node-sdk#16]
The example document operations show canceling an a document [here](https://github.com/eversign/eversign-node-sdk/blob/a21f5ee8d427bbec0d17fc1e5a415eaefbbf517d/examples/document_operations.js#L36):
```js
    client.cancelDocument(doc).catch(function(err) {
        console.log(err)
    });
```
However, the client code doesn't work, it always results in an unresolved promise. The relevant code is [here](https://github.com/eversign/eversign-node-sdk/blob/a21f5ee8d427bbec0d17fc1e5a415eaefbbf517d/lib/Client.js#L299):
```js
  this.deleteDocument = function (document, type) {
    return new Promise(function(resolve, reject) {
      getBusinessId().then(function (businessId) {
        if (!document.getDocumentHash()) {
          throw new Error('Deleting the Document requires the Document Hash');
        }
        if (!document.getIsDraft() && !document.getIsCanceled()) {
          throw new Error('Only Drafts and cancelled Documents can be deleted');
        }
        if (document.getIsDeleted()) {
          throw new Error('The Document has been deleted already');
        }
        var parameters = {
          "business_id" : businessId,
          "document_hash":  document.getDocumentHash()
        };
        if(type) {
          parameters[type] = 1;
        }
        var request = new ApiRequest("DELETE", accessKey, config.DOCUMENT_URL, undefined, $parameters);
        return request.startRequest().then(resolve).catch(reject);
      }).catch(function(err) {
        console.error(err)
      });
    });
  };

  this.cancelDocument = function (document) {
     return this.deleteDocument(document, "cancel");
  };
```
The two main issues are that the "cancel" argument passed for type in `cancelDocument` is never processed by `deleteDocument`, and the outermost catch just calls `console.error` but never rejects the promise.

I'm working around this by manually calling the API, but would be nice to have this fixed. I'll try and submit a pull a request if I find time but if ya'll can get to it that'd be great, thanks!

**Comment by parkerself22** [comment]
For anyone looking for a workaround, here's my solution (in typescript)
```ts
class Eversign {
     // ...rest of our internal implementation
    private async cancelAndDelete(documentHash: string) {
        const query = `?access_key=${this.config.EVERSIGN_KEY}&business_id=${this.config.BUSINESS_ID}&document_hash=${documentHash}`;
        const url = `https://api.eversign.com/api/document${query}`;

        const cancelResult = await axios.delete(`${url}&cancel=1`);
        if (cancelResult.data.success !== true) {
            throw new Error('Cancel eversign document failed');
        }
        const deleteResult = await axios.delete(url);
        if (deleteResult.data.success !== true) {
            throw new Error('Delete eversign document failed');
        }
        return true;
    }
}
```

**Comment by milanlatinovic** [comment]
Hi @parkerself22 

Thanks for reporting this while ago. 
I am commonly contributing to eversign PHP SDK and eversign Python SDK.
However, I saw this SDK has some  long-opened issues so I made a new release where this issue is resolved. 
Document cancellation works properly now.

Thanks for the workaround as well, it is much appreciated. 

Please try out release v.1.8.6 and let me know if this is fixing issue for you.
fyi  @danielmhanover, @Akuukis this might solve your issues so you do not have to use workaround any more.

All best everyone,
Milan

**Comment by Akuukis** [comment]
@milanlatinovic thanks! I'm not using this anymore so can't test to confirm.

**Comment by Akuukis** [comment]
@milanlatinovic Eversign was picked for it's friendly API (both technically and cost) as the company back then needed for it's automated and complicated usecase. It's not used anymore because that usecase went away, so the reason is not related to eversign really.

SDK could use lots of improvements, it was hard to work with and we ended up wrapping/rewritting it heavily internally (especially that error handling part). But hey, there's SDK at all and it's opensource, so you're already ahead of competitors (at least back, haven't checked market since)
